'use client'

import AppSideBar from "@/components/app.sidebar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Box, Container, CssBaseline, ThemeProvider } from "@mui/material";
import theme from "./theme";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CssBaseline />
        <ThemeProvider theme={theme}>
          <Box sx={{ display: "flex", height: "100%" }}>
            <AppSideBar />
            <Container
              maxWidth={false}
              sx={{ backgroundColor: "#ccc", height: "100%" }}>
              {children}
            </Container>
          </Box>

        </ThemeProvider>


      </body>
    </html>
  );
}
